DROP TABLE IF EXISTS quizzes CASCADE;
CREATE TABLE quizzes (
  id SERIAL PRIMARY KEY NOT NULL,
  owner_id INTEGER REFERENCES users(id) ON DELETE CASCADE NOT NULL,
  title VARCHAR(255) NOT NULL,
  description VARCHAR(255) DEFAULT '',
  date_created DATE DEFAULT NOW(),
  private BOOLEAN DEFAULT FALSE
);